/* Lobbyist - Curated demo bills across states */
/* Used for product demo across multiple industries and states */

const STATES = {
  "VA": "Virginia",
  "MD": "Maryland",
  "NC": "North Carolina",
  "TX": "Texas",
  "CA": "California"
};

const BILLS = [
  {
    state: "VA",
    bill: "HB 405",
    title: "Minimum wage increase to $13.50/hour",
    patron: "Del. Jones",
    category: "Labor",
    status: "In committee",
    effectiveDate: "2027-01-01",
    industries: ["restaurants", "retail", "childcare", "hospitality"],
    summary: "Increases Virginia minimum wage from $12.00 to $13.50 per hour.",
    impact: "Increases labor costs for all businesses with hourly staff.",
    urgency: "high",
    daysToVote: 3,
    lastUpdate: "2026-03-09",
    breaking: true
  },
  {
    state: "VA",
    bill: "SB 156",
    title: "Allergen labeling requirements for food service",
    patron: "Sen. Washington",
    category: "Health & Safety",
    status: "Enacted",
    effectiveDate: "2026-07-01",
    industries: ["restaurants", "cafes", "food service"],
    summary: "Restaurants must disclose top 8 allergens on menus or in writing.",
    impact: "Menu redesign and staff training required.",
    urgency: "medium",
    daysToVote: null,
    lastUpdate: "2026-02-15"
  },
  {
    state: "VA",
    bill: "HB 267",
    title: "Food handler licenses extended to 2-year validity",
    patron: "Del. Smith",
    category: "Health & Safety",
    status: "Enacted",
    effectiveDate: "2026-07-01",
    industries: ["restaurants", "food service", "hospitality"],
    summary: "Food handler certification now valid for 2 years instead of 1.",
    impact: "Reduces renewal burden and costs.",
    urgency: "low",
    daysToVote: null,
    lastUpdate: "2026-02-10"
  },
  {
    state: "VA",
    bill: "SB 89",
    title: "Tip pool disclosure requirement",
    patron: "Sen. Williams",
    category: "Labor",
    status: "Pending",
    effectiveDate: "2027-01-01",
    industries: ["restaurants", "hospitality"],
    summary: "Restaurants using tip pools must disclose the policy on menus or in writing.",
    impact: "Menu language change and staff communication required.",
    urgency: "medium",
    daysToVote: 12,
    lastUpdate: "2026-03-01"
  },
  {
    state: "VA",
    bill: "HB 512",
    title: "Childcare facility safety regulations",
    patron: "Del. Anderson",
    category: "Health & Safety",
    status: "In committee",
    effectiveDate: "2027-01-01",
    industries: ["childcare", "education"],
    summary: "Increases background check requirements and facility inspections for childcare centers.",
    impact: "Increased compliance costs and administrative burden.",
    urgency: "medium",
    daysToVote: 25,
    lastUpdate: "2026-02-28"
  },
  {
    state: "VA",
    bill: "HB 301",
    title: "Paid family leave requirement for employers",
    patron: "Del. Brown",
    category: "Labor",
    status: "Pending",
    effectiveDate: "2027-06-01",
    industries: ["all"],
    summary: "Employers must provide 8 weeks of paid leave for new parents.",
    impact: "Significant benefit cost and payroll planning impact.",
    urgency: "high",
    daysToVote: 18,
    lastUpdate: "2026-03-05"
  },
  {
    state: "VA",
    bill: "SB 234",
    title: "Independent contractor classification restrictions",
    patron: "Sen. Garcia",
    category: "Labor",
    status: "In committee",
    effectiveDate: "2027-01-01",
    industries: ["construction", "transportation", "gig economy"],
    summary: "Restricts ability to classify workers as independent contractors; aligns with ABC test.",
    impact: "May require reclassification of contractors to employees.",
    urgency: "high",
    daysToVote: 8,
    lastUpdate: "2026-03-08"
  },
  {
    state: "VA",
    bill: "HB 178",
    title: "Workplace violence prevention training",
    patron: "Del. Martinez",
    category: "Health & Safety",
    status: "Enacted",
    effectiveDate: "2026-09-01",
    industries: ["retail", "hospitality", "healthcare"],
    summary: "All employers must provide workplace violence prevention training annually.",
    impact: "Training time and potential compliance costs.",
    urgency: "medium",
    daysToVote: null,
    lastUpdate: "2026-02-20"
  },
  {
    state: "VA",
    bill: "HB 425",
    title: "Background check delays for employment",
    patron: "Del. Robinson",
    category: "Legal",
    status: "Enacted",
    effectiveDate: "2026-07-01",
    industries: ["all"],
    summary: "Employers cannot delay hiring based on pending background checks longer than 10 days.",
    impact: "May require faster hiring decisions.",
    urgency: "low",
    daysToVote: null,
    lastUpdate: "2026-02-12"
  },
  {
    state: "VA",
    bill: "SB 145",
    title: "Non-compete agreement restrictions",
    patron: "Sen. Lee",
    category: "Legal",
    status: "Pending",
    effectiveDate: "2027-01-01",
    industries: ["all"],
    summary: "Limits enforceability of non-compete agreements; focuses on reasonable restrictions.",
    impact: "May reduce ability to restrict employee movement.",
    urgency: "medium",
    daysToVote: 21,
    lastUpdate: "2026-03-02"
  },
  {
    state: "VA",
    bill: "HB 489",
    title: "Wage theft and illegal deduction penalties",
    patron: "Del. Thompson",
    category: "Labor",
    status: "In committee",
    effectiveDate: "2027-01-01",
    industries: ["all"],
    summary: "Increases penalties for wage theft and unauthorized payroll deductions.",
    impact: "Increased compliance risk; potential higher fines.",
    urgency: "medium",
    daysToVote: 14,
    lastUpdate: "2026-03-04"
  },
  {
    state: "VA",
    bill: "SB 167",
    title: "Pregnant worker accommodations",
    patron: "Sen. Jackson",
    category: "Labor",
    status: "Enacted",
    effectiveDate: "2026-07-01",
    industries: ["all"],
    summary: "Employers must provide reasonable accommodations for pregnancy-related conditions.",
    impact: "New requirement to assess and provide accommodations.",
    urgency: "low",
    daysToVote: null,
    lastUpdate: "2026-02-18"
  },
  {
    state: "VA",
    bill: "HB 556",
    title: "Retail worker schedule predictability",
    patron: "Del. Pierce",
    category: "Labor",
    status: "Pending",
    effectiveDate: "2027-01-01",
    industries: ["retail", "hospitality"],
    summary: "Requires retailers to provide employee schedules 2 weeks in advance.",
    impact: "Scheduling system changes and potential staffing impacts.",
    urgency: "medium",
    daysToVote: 16,
    lastUpdate: "2026-03-06"
  },
  {
    state: "VA",
    bill: "HB 390",
    title: "Contractor payment requirements",
    patron: "Del. Hall",
    category: "Legal",
    status: "In committee",
    effectiveDate: "2027-01-01",
    industries: ["construction", "services"],
    summary: "Construction contractors must pay subcontractors within 7 days of payment receipt.",
    impact: "May accelerate cash flow requirements.",
    urgency: "medium",
    daysToVote: 11,
    lastUpdate: "2026-03-03"
  },
  {
    state: "MD",
    bill: "HB 220",
    title: "Service fee disclosure on restaurant checks",
    patron: "Del. Carter",
    category: "Legal",
    status: "In committee",
    effectiveDate: "2027-01-01",
    industries: ["restaurants", "hospitality"],
    summary: "Restaurants must disclose all automatic service fees before ordering, in plain language.",
    impact: "Menu and receipt updates; possible fee restructuring.",
    urgency: "high",
    daysToVote: 6,
    lastUpdate: "2026-03-07",
    breaking: true
  },
  {
    state: "MD",
    bill: "SB 310",
    title: "Retail organized theft penalties",
    patron: "Sen. Okafor",
    category: "Legal",
    status: "Pending",
    effectiveDate: "2026-10-01",
    industries: ["retail"],
    summary: "Increases penalties for organized retail theft and creates a state task force.",
    impact: "Generally favorable; may reduce shrink losses.",
    urgency: "low",
    daysToVote: 20,
    lastUpdate: "2026-03-02"
  },
  {
    state: "NC",
    bill: "H 142",
    title: "Childcare staff-to-child ratio changes",
    patron: "Rep. Bell",
    category: "Health & Safety",
    status: "In committee",
    effectiveDate: "2027-01-01",
    industries: ["childcare", "education"],
    summary: "Tightens staff-to-child ratios for children under 3 in licensed childcare facilities.",
    impact: "May require additional staff hires per classroom.",
    urgency: "high",
    daysToVote: 9,
    lastUpdate: "2026-03-06"
  },
  {
    state: "TX",
    bill: "HB 890",
    title: "Contractor licensing reciprocity",
    patron: "Rep. Trevino",
    category: "Legal",
    status: "Pending",
    effectiveDate: "2027-01-01",
    industries: ["construction"],
    summary: "Recognizes out-of-state contractor licenses for firms in good standing.",
    impact: "Easier expansion into Texas; more competition in-state.",
    urgency: "medium",
    daysToVote: 30,
    lastUpdate: "2026-03-01"
  },
  {
    state: "CA",
    bill: "AB 512",
    title: "Fast food council wage standards expansion",
    patron: "Asm. Nguyen",
    category: "Labor",
    status: "In committee",
    effectiveDate: "2027-01-01",
    industries: ["restaurants", "hospitality"],
    summary: "Expands fast food council authority to set wage and scheduling standards for chains with 40+ locations.",
    impact: "Potential wage floor increases for franchise operators.",
    urgency: "high",
    daysToVote: 15,
    lastUpdate: "2026-03-05"
  }
];

const BILL_TOPICS = {
  "Labor": "Labor law, wages, and working conditions",
  "Health & Safety": "Employee and customer safety",
  "Legal": "Legal and compliance matters",
  "Education": "Educational requirements"
};

const LEGISLATORS = {
  "Del. Jones": { chamber: "House", district: "Arlington" },
  "Sen. Washington": { chamber: "Senate", district: "Downtown Richmond" },
  "Del. Smith": { chamber: "House", district: "Fairfax" },
  "Sen. Williams": { chamber: "Senate", district: "Northern Virginia" },
  "Del. Anderson": { chamber: "House", district: "Alexandria" },
  "Del. Brown": { chamber: "House", district: "Richmond" },
  "Sen. Garcia": { chamber: "Senate", district: "Central Virginia" },
  "Del. Martinez": { chamber: "House", district: "Henrico" },
  "Del. Robinson": { chamber: "House", district: "Northern Virginia" },
  "Sen. Lee": { chamber: "Senate", district: "Southwest Virginia" },
  "Del. Thompson": { chamber: "House", district: "Petersburg" },
  "Sen. Jackson": { chamber: "Senate", district: "South Hampton Roads" },
  "Del. Pierce": { chamber: "House", district: "Virginia Beach" },
  "Del. Hall": { chamber: "House", district: "Hampton Roads" }
};